### ISSUE TITLE
Support `allow-multiple` in query params

### ISSUE THREAD

**Issue by dsinghvi** [fern-api/fern-typescript#215]
For the following request: 
```yaml
request:
    name: MyRequest
    query-parameters:
       myParameter:
         type: integer
         allow-multiple: true
```
the generated sdk should have represent this parameter as a `integer[]` and serialization should result in a url that looks like 
```javascript
`myParameter=${list[0]}&myParameter=${list[1]}`
```
