### ISSUE TITLE
[Bug] Schemas fields are generated in camelCase despite `noSerdeLayer` is enabled

### ISSUE THREAD

**Issue by krugi** [fern-api/fern-typescript#629]
**Describe the bug**
I noticed some schemas have their fields converted camelCase, despite `noSerdeLayer` is enabled, while others are generated in snake_case as expected. 

For example, this schema:
```json
"CreateClassRequestSchema": {
  "title": "CreateClassRequestSchema",
  "required": [
    "name",
    "category",
    "sensitivity_weight",
    "classifier_schema"
  ],
  "type": "object",
  "properties": {
    "name": {
      "title": "Name",
      "type": "string"
    },
    "description": {
      "title": "Description",
      "type": "string",
      "default": ""
    },
    "category": {
      "$ref": "#/components/schemas/ClassCategories"
    },
    "sensitivity_weight": {
      "title": "Sensitivity Weight",
      "type": "integer"
    },
    "enabled": {
      "title": "Enabled",
      "type": "boolean",
      "default": true
    },
    "classifier_schema": {
      "title": "Classifier Schema",
      "oneOf": [
        {
          "$ref": "#/components/schemas/CreateRegexClassifierRequestSchema"
        },
        {
          "$ref": "#/components/schemas/CreateDictionaryClassifierRequestSchema"
        }
      ],
      "discriminator": {
        "propertyName": "type",
        "mapping": {
          "REGEX": "#/components/schemas/CreateRegexClassifierRequestSchema",
          "DICTIONARY": "#/components/schemas/CreateDictionaryClassifierRequestSchema"
        }
      }
    }
  }
},
```
_(I rather not provide the entire openapi.json I used as it's internal)_ 

Is generated as (notice sensitivityWeight and classifierSchema):
```typescript
export interface CreateClassRequestSchema {
    name: string;
    description?: string;
    category: MyApi.ClassCategories;
    sensitivityWeight: number;
    enabled?: boolean;
    classifierSchema: MyApi.CreateClassRequestSchemaClassifierSchema;
}
```

**To Reproduce**
I ran `task generate` with the following settings:
```yaml
default-group: local
groups:
  local:
    generators:
      - name: fernapi/fern-typescript-browser-sdk
        version: 0.7.2
        output:
          location: local-file-system
          path: ../frontend/generated/api
        config:
          outputEsm: true
          noSerdeLayer: true
```

**Expected behavior**
Should be generated as:
```typescript
export interface CreateClassRequestSchema {
    name: string;
    description?: string;
    category: MyApi.ClassCategories;
    sensitivity_weight: number;
    enabled?: boolean;
    classifier_schema: MyApi.CreateClassRequestSchemaClassifierSchema;
}
```

**Versions**
 - Fern CLI: 0.15.3
 - Generator: 0.7.2

**Additional context**
